'use client'

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { getLocale } from './util'
import { useState } from 'react'
import Sidebar from './home/sidebar'
import Navbar from './home/navbar'
import { Locale, i18n } from '@/i18n-config'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export async function generateStaticParams () {
  return i18n.locales.map(lang => {
    lang
  })
}

export default function RootLayout ({
  children,
  params
}: {
  children: React.ReactNode
  params: { lang: Locale }
}) {
  const [sidebarOpen, setSidebarOpen] = useState(false)
  return (
    <html lang={params.lang}>
      <body className={inter.className}>
        <div className='grid min-h-screen grid-rows-header bg-zinc-100'>
          <Navbar onMenuButtonClick={() => setSidebarOpen(b => !b)} />
          <div className='grid row-start-2 md:grid-cols-sidebar'>
            <Sidebar open={sidebarOpen} setOpen={setSidebarOpen}></Sidebar>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
