
type ValidTextCategory =
  | 'AdvertisementText'
  | 'ApText'
  | 'AppointmentText'
  | 'ArText'
  | 'AreaText'
  | 'AttributeText'
  | 'BannerText'
  | 'BgmText'
  | 'BoostGroupText'
  | 'CampText'
  | 'CampaignText'
  | 'CardText'
  | 'ChallengeText'
  | 'ChapterText'
  | 'CharaNaviText'
  | 'CollectionText'
  | 'CommonText'
  | 'ConfessionText'
  | 'CraftText'
  | 'FeatureText'
  | 'FeedText'
  | 'FuncText'
  | 'GachaText'
  | 'GearText'
  | 'GrowthRewardText'
  | 'GuideMissionText'
  | 'GuildCampText'
  | 'GuildText'
  | 'HelpText'
  | 'HomeBgmText'
  | 'HomeLayoutText'
  | 'HomeText'
  | 'InvitationText'
  | 'ItemText'
  | 'LocationText'
  | 'LoginText'
  | 'LotteryText'
  | 'MemberText'
  | 'PhotoText'
  | 'PlayerTitleText'
  | 'ProfileText'
  | 'PuzzleText'
  | 'QuestText'
  | 'ReactionText'
  | 'RelationshipText'
  | 'RewardText'
  | 'SeasonText'
  | 'SeriesText'
  | 'ShopTabText'
  | 'ShopText'
  | 'SituationText'
  | 'SkillText'
  | 'SpecialContentText'
  | 'SpecialDialogText'
  | 'StageText'
  | 'StampText'
  | 'StickerText'
  | 'StillPictureText'
  | 'StoryText'
  | 'TeamBattleText'
  | 'TipsText'
  | 'UnitText'
  | 'VrText'
  | 'WorkText'
  | 'YpText'

export function textMap (this: any, cat: ValidTextCategory, id?: number) {
  const nil = '�'
  if (id == null) return nil
  const text = this?.[cat]?.map?.[id]
  if (typeof text !== 'string') return nil
  return text
}

export type TextMap = typeof textMap
